---
{{- with $.Values }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  app: {{ .name }}
  name: {{ .name }}-secret
  labels:
    {{- range $label := $.Values.global.labels }}
    {{ $label.key }} : {{ tpl $label.value $ }}
    {{- end}}
type: Opaque
data:
  postgresqlUsername: {{ .postgresqlUsername | b64enc | quote }}
  postgresqlPassword: {{ .postgresqlPassword | b64enc | quote }}
  postgresqlDatabase: {{ .postgresqlDatabase | b64enc | quote }}
{{- end -}}
{{- end -}}
