---
{{- with $.Values }}
{{- if .enabled }}
apiVersion: apps.openshift.io/v1 
kind: DeploymentConfig
metadata:
  labels:
    app: {{ $.Values.global.appname }}
    name: {{ .name }}
    deploymentconfig: {{ .name }}
    {{- range $label := $.Values.global.labels }}
    {{ $label.key }} : {{ tpl $label.value $ }}
    {{- end}}
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    app: {{ $.Values.global.appname }}
    deploymentconfig: {{ .name }}
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $.Values.global.appname }}
        name: {{ .name }}
        deploymentconfig: {{ .name }}
    spec:
      containers:
        - name: postgresql
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: postgresqlUsername
                  name: {{ .name }}-secret
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresqlPassword
                  name: {{ .name }}-secret
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: postgresqlDatabase
                  name: {{ .name }}-secret
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .service.port | default "5432" }}
            timeoutSeconds: 1
          ports:
            - containerPort: {{ .service.port  | default "5432" }}
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -i
                - -c
                - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgresql
        from:
          kind: ImageStreamTag
          {{- $image:=.image }}
          name: postgresql:{{ .tag | default "9.6" }}
          namespace: openshift
      type: ImageChange
{{- end }}
{{- end }}